sudo: false
dist: xenial
language: python
group: edge
python: 
 - 3.4
 - 3.5

matrix:
  include:
    - os: linux
      python: 3.5
      env: TESTENV=py35-pyqt571 QT_API=pyqt5 PEP8=1 COV=1
    - os: linux
      language: generic
      env: TESTENV=shellcheck
  fast_finish: true

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/videomorph/videomorph/.cache

install:
  - pip install pip --upgrade
  - pip install nose flake8 pep8-naming flake8-debugger flake8-docstrings codecov

script:
  - flake8 --select=D1 videomorph/*.py

after_success:
  - '[[ $TESTENV == *-cov ]] && codecov -e TESTENV -X gcov'
